
version: '2'
services:
  kaiwa:
    container_name: kaiwa
    env_file: ./envs/local.env
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/kaiwa
    ports:
      - "8000:8000"
    links:
      - postgres
      - mongo

  postgres:
    container_name: kaiwa-postgres
    image: postgres:9.6
    env_file: ./envs/local.env
    volumes:
      - postgres:/var/lib/postgresql/data/

  mongo:
    container_name: kaiwa-mongo
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27018:27017"

volumes:
  postgres:
  mongo:
