# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('lis_result_sourcedid', models.CharField(db_index=True, max_length=255)),
                ('version_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_outcome_service_url', models.CharField(max_length=255, unique=True)),
                ('lti_consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_provider.LtiConsumer')),
            ],
        ),
        migrations.AddField(
            model_name='gradedtask',
            name='outcome_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_provider.OutcomeService'),
        ),
        migrations.AddField(
            model_name='gradedtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gradedtask',
            unique_together=set([('outcome_service', 'lis_result_sourcedid')]),
        ),
    ]
