# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_provider', '0002_auto_20170907_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradedtask',
            unique_together=set([('outcome_service', 'lis_result_sourcedid', 'task_id')]),
        ),
    ]
